# Generated by Django 5.2.11 on 2026-02-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastschedule',
            options={'ordering': ['next_send', 'start_date'], 'verbose_name': 'Broadcast Schedule', 'verbose_name_plural': 'Broadcast Schedules'},
        ),
        migrations.AlterModelOptions(
            name='holidaynotice',
            options={'ordering': ['-start_date'], 'verbose_name': 'Holiday Notice', 'verbose_name_plural': 'Holiday Notices'},
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastschedule',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='No content available'),
        ),
        migrations.AddField(
            model_name='notification',
            name='holiday_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_messages.holidaynotice'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='short_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school_messages.message'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='school_mess_user_id_8d0f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='school_mess_user_id_c867b3_idx'),
        ),
    ]
