# Generated by Django 5.2.11 on 2026-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_role',
            field=models.CharField(blank=True, choices=[('teacher', 'Regular Teacher'), ('deputy_principal', 'Deputy Principal'), ('hod', 'Head of Department'), ('sports_master', 'Sports Master'), ('academic_head', 'Academic Head'), ('discipline_master', 'Discipline Master'), ('activity_coordinator', 'Activity Coordinator')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
