# Generated by Django 5.2.11 on 2026-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='marks.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_roles',
            field=models.TextField(blank=True, help_text='Additional roles and responsibilities'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extracurricular_activities',
            field=models.TextField(blank=True, help_text='Extracurricular activities supervised'),
        ),
    ]
