# Generated by Django 5.2.10 on 2026-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_assigned_subjects_teacher_extra_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='initial_password',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
