# Generated by Django 5.2.11 on 2026-02-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('current_term_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_term_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable'), ('fluctuating', 'Fluctuating'), ('significant_improvement', 'Significant Improvement'), ('significant_decline', 'Significant Decline'), ('gradual_improvement', 'Gradual Improvement'), ('gradual_decline', 'Gradual Decline')], default='stable', max_length=30)),
                ('trend_direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('score_change', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute change in average score', max_digits=6, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from previous term', max_digits=6, null=True)),
                ('strongest_subject_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weakest_subject_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('improvement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subjects_passed', models.PositiveIntegerField(default=0)),
                ('total_subjects', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_a_count', models.PositiveIntegerField(default=0)),
                ('grade_b_count', models.PositiveIntegerField(default=0)),
                ('grade_c_count', models.PositiveIntegerField(default=0)),
                ('grade_d_count', models.PositiveIntegerField(default=0)),
                ('grade_e_count', models.PositiveIntegerField(default=0)),
                ('grade_f_count', models.PositiveIntegerField(default=0)),
                ('strengths', models.TextField(blank=True, help_text='Key strengths observed')),
                ('weaknesses', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('analysis_summary', models.TextField(blank=True, help_text='Overall performance analysis')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('action_items', models.TextField(blank=True, help_text='Specific action items')),
                ('is_active', models.BooleanField(default=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('most_improved_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_most_improved', to='marks.subject')),
                ('strongest_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_strongest_subject', to='marks.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to='students.student')),
                ('weakest_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_weakest_subject', to='marks.subject')),
            ],
            options={
                'verbose_name': 'Performance Trend',
                'verbose_name_plural': 'Performance Trends',
                'ordering': ['-academic_year', 'term', 'student'],
                'indexes': [models.Index(fields=['student', 'trend'], name='marks_perfo_student_e35df1_idx'), models.Index(fields=['student', 'academic_year'], name='marks_perfo_student_c9ac58_idx'), models.Index(fields=['trend_direction', 'date_generated'], name='marks_perfo_trend_d_227989_idx')],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
    ]
